### ISSUE TITLE
Unhandled promise rejection: DB closed

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.dwd#77]
**Describe the bug**  
Nachts um 04.30 führt Proxmox ein Backup vom ioBroker Container durch.

Proxmox Backup Konfiguration für den Container:
![grafik](https://user-images.githubusercontent.com/25422320/113204484-98f1b500-926d-11eb-883b-70cbab9996a1.png)

Am 30.03 kamen dann die im Logfile gezeigten Errors. Unter anderem: 
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). und "unhandled promise rejection: DB closed"

Mich hat die Meldung "Error: DB closed at Redis.sendCommand....." irritiert, da ich in diesem ioBroker Container kein Redis verwende (siehe auch Abschnitt Versions)

**Expected behavior**  
Keine Unhandled promise rejections :-)

**Versions:**  
 js-controller: 3.2.16
 node: 12.21.0 
nodejs: v12.21.0
npm: 6.14.11 
Admin: 4.2.1 
Java Script Enging: 5.1.3 
DWD 2.7.5 

```
proxmox@ioBrokerBETA:~$ iobroker status
iobroker is running on this host.
Objects type: file
States  type: file
```

**Screenshots & Logfiles**  

```

30 Mar 2021 04:30:08.914
host.beebox(iobrokerMaster) instance system.adapter.dwd.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
30 Mar 2021 04:30:08.455
host.beebox(iobrokerMaster) instance system.adapter.admin.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
30 Mar 2021 04:30:08.450
host.beebox(iobrokerMaster) instance system.adapter.simple-api.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
30 Mar 2021 04:30:08.222
host.beebox(iobrokerMaster) instance system.adapter.scenes.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP) 
30 Mar 2021 04:30:07.927
dwd.0 (31515) DB closed
30 Mar 2021 04:30:07.926
dwd.0 (31515) Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:607:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:111:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:477:40) at Adapter.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6395:35)
30 Mar 2021 04:30:07.871
dwd.0 (31515) unhandled promise rejection: DB closed
30 Mar 2021 04:30:07.866
dwd.0 (31515) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
30 Mar 2021 04:30:07.847
dwd.0 (31515) get state error: Connection is closed.
30 Mar 2021 04:30:07.841
dwd.0 (31515) Could not check object existence of state dwd.0.numberofwarnings: Cannot check object existence of "dwd.0.numberofwarnings": Connection is closed.
30 Mar 2021 04:30:07.836
dwd.0 (31515) Cannot check object existence of "dwd.0.numberofwarnings": Connection is closed.
30 Mar 2021 04:30:07.797
host.beebox(iobrokerMaster) stopInstance system.adapter.mqtt.0 killing pid 1157
30 Mar 2021 04:30:07.795
host.beebox(iobrokerMaster) stopInstance system.adapter.hm-rega.0 killing pid 550
30 Mar 2021 04:30:07.793
host.beebox(iobrokerMaster) stopInstance system.adapter.telegram.0 killing pid 1942
30 Mar 2021 04:30:07.792
host.beebox(iobrokerMaster) stopInstance system.adapter.fritzbox.0 killing pid 501
30 Mar 2021 04:30:07.790
host.beebox(iobrokerMaster) stopInstance system.adapter.javascript.0 killing pid 478
30 Mar 2021 04:30:07.788
host.beebox(iobrokerMaster) stopInstance system.adapter.tankerkoenig.0 killing pid 418
30 Mar 2021 04:30:06.895
host.beebox(iobrokerMaster) instance system.adapter.hm-rpc.0 terminated with code null ()
30 Mar 2021 04:30:06.894
host.beebox(iobrokerMaster) instance system.adapter.hm-rpc.0 terminated due to SIGTERM
30 Mar 2021 04:30:06.522
host.beebox(iobrokerMaster) stopInstance timeout 1000 system.adapter.hm-rpc.0 killing pid 535
30 Mar 2021 04:30:06.493
host.beebox(iobrokerMaster) instance system.adapter.influxdb.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
30 Mar 2021 04:30:06.153
host.beebox(iobrokerMaster) stopInstance system.adapter.web-speedy.0 send kill signal
30 Mar 2021 04:30:06.152
host.beebox(iobrokerMaster) stopInstance system.adapter.samsung-community.0 send kill signal
30 Mar 2021 04:30:06.151
host.beebox(iobrokerMaster) stopInstance system.adapter.mqtt.0 send kill signal
30 Mar 2021 04:30:06.150
host.beebox(iobrokerMaster) stopInstance system.adapter.simple-api.0 send kill signal
30 Mar 2021 04:30:06.149
host.beebox(iobrokerMaster) stopInstance system.adapter.hue.0 send kill signal
30 Mar 2021 04:30:06.148
host.beebox(iobrokerMaster) stopInstance system.adapter.unifi.0 send kill signal
30 Mar 2021 04:30:06.147
host.beebox(iobrokerMaster) stopInstance system.adapter.fully-tablet-control.0 send kill signal
30 Mar 2021 04:30:06.146
host.beebox(iobrokerMaster) stopInstance system.adapter.trashschedule.0 send kill signal
30 Mar 2021 04:30:06.145
host.beebox(iobrokerMaster) stopInstance system.adapter.logparser.0 send kill signal
30 Mar 2021 04:30:06.145
host.beebox(iobrokerMaster) stopInstance system.adapter.tr-064.0 send kill signal
30 Mar 2021 04:30:06.144
host.beebox(iobrokerMaster) stopInstance system.adapter.socketio.0 send kill signal
30 Mar 2021 04:30:06.143
host.beebox(iobrokerMaster) stopInstance system.adapter.proxmox.0 send kill signal
30 Mar 2021 04:30:06.142
host.beebox(iobrokerMaster) stopInstance system.adapter.scenes.0 send kill signal
30 Mar 2021 04:30:06.141
host.beebox(iobrokerMaster) stopInstance system.adapter.info.0 send kill signal
30 Mar 2021 04:30:06.140
host.beebox(iobrokerMaster) stopInstance system.adapter.valloxmv.0 send kill signal
30 Mar 2021 04:30:06.139
host.beebox(iobrokerMaster) stopInstance system.adapter.hm-rega.0 send kill signal
30 Mar 2021 04:30:06.138
host.beebox(iobrokerMaster) stopInstance system.adapter.telegram.0 send kill signal
30 Mar 2021 04:30:06.137
host.beebox(iobrokerMaster) stopInstance system.adapter.fritzbox.0 send kill signal
30 Mar 2021 04:30:06.136
host.beebox(iobrokerMaster) stopInstance system.adapter.javascript.0 send kill signal
30 Mar 2021 04:30:06.135
host.beebox(iobrokerMaster) stopInstance system.adapter.tankerkoenig.0 send kill signal
30 Mar 2021 04:30:06.134
host.beebox(iobrokerMaster) stopInstance system.adapter.web.0 send kill signal
30 Mar 2021 04:30:06.084
javascript.0 (478) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
30 Mar 2021 04:30:06.078
host.beebox(iobrokerMaster) stopInstance system.adapter.admin.0 send kill signal
30 Mar 2021 04:30:06.055
dwd.0 (31515) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason 
```

**Comment by GermanBluefox** [comment]
It depends on js-controller. Now with 3.3.x must be fixed

**Comment by Feuer-sturm** [comment]
In log file of testsystem with js-controller 3.3.x the error is not available. Issue closed.
